routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('test', 'TestController@test');
Route::get('/', function () {
    return view('auth.login');
});

Route::get('/main_home', function () {
    return view('main_home');
});

Route::get('/contact', function () {
    return view('contact');
});

// Route::get('/contact','MessageController@index');
Route::get('/storeContact','MessageController@storeContact');
Route::get('/AMR.view_messages','MessageController@showContact');



Route::get('/about', function () {
    return view('about');
});

Route::get('/login', function () {
    return view('login');
});

Route::get('/aaa', function () {
    return view('aaa');
});

Route::get('/register1', function () {
    return view('register1');
});

Route::get('/schedule', function () {
    return view('schedule');
});

Route::get('/pending', function () {
    return view('pending');
});


//AMR TABS
Route::get('/amrhome', function () {
    return view('AMR.amrhome');
})->name('AMR.amrhome');

Route::get('/pending_list', function () {
    return view('AMR.pending_list');
})->middleware('auth');

Route::get('/staff_list', function () {
    return view('AMR.staff_list');
})->middleware('auth');

Route::get('/create_audit', function () {
    return view('AMR.create_audit');
})->middleware('auth');

Route::get('/view_schedule', function () {
    return view('AMR.view_schedule');
});


Route::get('/select_auditor', function () {
    return view('AMR.select_auditor');
});

Route::get('/auditor_list', function () {
    return view('AMR.auditor_list');
});

Route::get('/notification', function () {
    return view('AMR.notification');
});

Route::get('/view_messages', function () {
    return view('AMR.view_messages');
});

Route::get('/view_report', function () {
    return view('AMR.view_report');
});

Route::get('/view_report1', function () {
    return view('AMR.view_report1');
});


//AUDITEE TABS
Route::get('/AUDITEE.auditee_home', function () {
    return view('AUDITEE.auditee_home');
})->name('AUDITEE.auditee_home');

Route::get('/AUDITEE.auditee_profile', function () {
    return view('AUDITEE.auditee_profile');
});

Route::get('/AUDITEE.notification', function () {
    return view('AUDITEE.notification');
});

Route::get('/AUDITEE.view_generalinfo', function () {
    return view('AUDITEE.view_generalinfo');
});

Route::get('/AUDITEE.view_checklist', function () {
    return view('AUDITEE.view_checklist');
});

Route::get('/AUDITEE.view_report', function () {
    return view('AUDITEE.view_report');
});

Route::get('/AUDITEE.view_schedule', function () {
    return view('AUDITEE.view_schedule');
});

//IQAC TABS
Route::get('/IQAC.iqac_home', function () {
    return view('IQAC.iqac_home');
})->name('IQAC.iqac_home');

Route::get('/IQAC.iqac_profile', function () {
    return view('IQAC.iqac_profile');
});

Route::get('/IQAC.notification', function () {
    return view('IQAC.notification');
});

Route::get('/IQAC.view_schedule', function () {
    return view('IQAC.view_schedule');
});

Route::get('/IQAC.view_auditors', function () {
    return view('IQAC.view_auditors');
});

Route::get('/IQAC.view_report', function () {
    return view('IQAC.view_report');
});


//IQAC COORDINATOR TABS
Route::get('/IQACCo.iqacco_home', function () {
    return view('IQACCo.iqacco_home');
})->name('IQACCo.iqacco_home');

Route::get('/IQACCo.iqacco_profile', function () {
    return view('IQACCo.iqacco_profile');
});

Route::get('/IQACCo.send_notification', function () {
    return view('IQACCo.send_notification');
});

Route::get('/IQACCo.view_schedule', function () {
    return view('IQACCo.view_schedule');
});

Route::get('/IQACCo.view_auditors', function () {
    return view('IQACCo.view_auditors');
});

Route::get('/IQACCo.view_report', function () {
    return view('IQACCo.view_report');
});

//AUDITOR TABS
Route::get('/AUDITOR.auditor_home', function () {
    return view('AUDITOR.auditor_home');
})->name('AUDITOR.auditor_home');

Route::get('/AUDITOR.notes', function () {
    return view('AUDITOR.notes');
});

Route::get('/AUDITOR.form1', function () {
    return view('AUDITOR.form1');
});

Route::POST('/AUDITOR.form2', function () {
    return view('AUDITOR.form2');
});

Route::get('/AUDITOR.form3', function () {
    return view('AUDITOR.form3');
});

// routes for contact blade.
Route::get('/contact', 'MessageController@index');
Route::post('/storeContact', 'MessageController@storeContact');
Route::get('/view_messages', 'MessageController@showContact');

//route for create audit
Route::get('/create_audit', 'CreateAuditController@index');
Route::post('insert', 'CreateAuditController@insert');
Route::get('/destroyAudit/{id}','CreateAuditController@destroyAudit');
//login route
Route::post('/loginCustom','CustomLoginController@login')->name("loginCustom");


//rout for register blade
Route::get('/register', 'RegisterController@index');  //for display registration form
Route::post('/registration','RegisterController@registration');  //for storing values


//route for pending list
Route::get('/pending_list', 'PendingListController@show');  //for display registration form
Route::get('/update/{id}','PendingListController@update');
Route::get('/destroy/{id}','PendingListController@destroy');

//registered list
Route::get('/staff_list','RegisteredListController@index');
Route::get('/staff_list','RegisteredListController@show');
Route::get('/setIQAC/{id}','RegisteredListController@setIQAC');
Route::get('/setAuditee/{id}','RegisteredListController@setAuditee');

//rout for auditor selection blade
Route::get('/select_auditor','AuditorSelectionController@index');
Route::get('/select_auditor','AuditorSelectionController@show');
Route::post('show_schedule', 'AuditorSelectionController@showDepartmentAudit');
Route::post('store_date', 'AuditorSelectionController@storeDate');
Route::post('role/auditor', 'AuditorSelectionController@departmentAuditor');
Route::post('viewSchedule', 'AuditorSelectionController@viewSchedule');
Route::get('schedulepdf/pdf/{id}', 'AuditorSelectionController@pdf');


//IQAC Home routes
Route::post('viewIQACSchedule', 'AuditorSelectionController@viewIQACSchedule');

//IQACCo Home routes
Route::post('viewIQACCoSchedule', 'AuditorSelectionController@viewIQACCoSchedule');
Route::post('resultIQACCo', 'KeyAspectController@resultIQACCo');
Route::post('view_reportIqacco','KeyAspectController@departmentReportIQACCo');

//AUDITEE Home routes
Route::post('viewAuditeeSchedule', 'AuditorSelectionController@viewAuditeeSchedule');


//Route for RoleController
// Route::get('/AMR.staff_list','RoleController@index');
Route::post('role/store','RoleController@store');

//Route for generating keyAspects
Route::post('generate','KeyAspectController@generate');
Route::post('valuation','KeyAspectController@keyAspectupdate');
Route::post('result','KeyAspectController@viewReport');
Route::post('view_report1','KeyAspectController@departmentReport');
Route::get('report/Pdf/{id}','ReportController@Pdf');
Route::POST('sendNotification','NotificationController@sendNotification');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');




Route::get('/view_report1', function () {
    return view('AMR.view_report1');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    public function department(){
      return $this->belongsTo('App\Department');
    }

    public function departmentAudit(){
        return $this->belongsToMany('App\DepartmentAudit','department_audit_auditors');
    }

    public function getFullnameAttribute(){
        return $this->name." ".$this->lname;
    }

    public function getIsAuditorAttribute(){
        return ($this->departmentAudit->count() > 0 ? true : false);
    }

    public function roles(){
        return $this->belongsToMany('App\Role');
    }

    public function getIsAmrAttribute(){
        foreach ($this->roles as $role) {
            if ($role->name == "AMR") {
              return true;
            }
        }
        return false;
    }

    public function getIsIQACAttribute(){
        foreach ($this->roles as $role) {
            if ($role->name == "IQAC") {
              return true;
            }
        }
        return false;
    }

    public function getIsIQACCoAttribute(){
        foreach ($this->roles as $role) {
            if ($role->name == "IQACCo") {
              return true;
            }
        }
        return false;
    }

    public function getIsAuditeeAttribute(){
        foreach ($this->roles as $role) {
            if ($role->name == "Auditee") {
              return true;
            }
        }
        return false;
    }

    public function getRoleNamesAttribute(){
        $role_names = "";
        foreach ($this->roles as $role) {
            $role_names .= $role->name.", ";
        }
        return rtrim($role_names, ", ");
    }

    

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/about.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="css/style.css">  
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    
/* Style the navbar */
#navbar {
  overflow: hidden;
  background-color: #333;
}

/* Navbar links */
#navbar a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px;
  text-decoration: none;
}

/* Page content */
.content {
  padding: 120px 500px;
}

/* The sticky class is added to the navbar with JS when it reaches its scroll position */
.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}

/* Add some top padding to the page content to prevent sudden quick movement (as the navigation bar gets a new position at the top of the page (position:fixed and top:0) */
.sticky + .content {
  padding-top: 60px;
}

/* Style the navigation bar */
.navbar {
  width: 100%;
  background-color: #0008;
  overflow: auto;
}

/* Navbar links */
.navbar a {
  float: left;
  text-align: center;
  padding: 12px;
  color: white;
  text-decoration: none;
  font-size: 17px;
}

/* Navbar links on mouse-over */
.navbar a:hover {
  background-color: #000;
}

/* Current/active navbar link */
.active {
  background-color: skyblue;
}

/* Add responsiveness - will automatically display the navbar vertically instead of horizontally on screens less than 500 pixels */
@media screen and (max-width: 500px) {
  .navbar a {
    float: none;
    display: block;
  }
}


.footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    height: 6%;
    background-color: #0008;
    color: black;
    text-align: center;
}
  </style>
  
  </head>
  <body>

<!-- Header -->
<div class="navbar">
  <a href="{{url('/')}}"><i class="fa fa-fw fa-home"></i> Home</a> 
 </div>  

    <div class="container">
      <h1 class="ias">IAS</h1>
        <p>The Departments of any institution are the backbone of the core business of any institution where trifocal activities (teaching, learning, research and service) are executed. Academic audit is a mechanism to examine the overall quality of an institution and subsequence improvements to be made based on the observations reported. It is a continuous process of self-introspection for better growth of the institution. Here we introduce an INTERNAL AUDITING SYSTEM, a web application to enhance the activities associated with it</p>
        <p>IAS provides a systematic process of scheduling, implementing, monitoring and reviewing the quality of academic system. The selection of auditor and auditee, audit process and report generation can be performed using this system. Through this project we can reduce the paper work and time, effectively communicate and made easy to use.</p>

    </div>

<!-- Footer -->>
<div class="footer">
  <p>&copy Copyright protected by BiGOne IT SolutionS</p>
  </div>


  </body>
</html>

resources/views/auditeenotification.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  @include('headerfooter')
  <link rel="shortcut icon" href="IASttl1.png"/>
  <title>AUDITEE-NOTIFICATIONS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="/css/amrstyle.css">
  <link rel="stylesheet" href="/css/amr.css">
</head>
<body>

<!-- Side Navbar -->
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>AUDITEE HOME</h4>
      <ul class="nav nav-pills nav-stacked">
        <li ><a href="AUDITEE.auditee_profile">Profile</a></li>
        <li class="active"><a href="AUDITEE.notification">Notifications</a></li>
        <li><a href="AUDITEE.view_generalinfo">General Informations</a></li>
        <li><a href="AUDITEE.view_checklist">Checklist</a></li>
        <li><a href="AUDITEE.view_report">Audit Report</a></li>
      </ul><br>
    </div>

<!-- Table Content -->
    <div class="col-sm-9">
      <h4><small>NOTIFICATIONS</small></h4>
      <hr>

    </div>
  </div>


<!-- footer -->
<footer class="container-fluid">
  <p>Powered By BiGOne IT SolutionS</p>
</footer>
</div>
</body>
</html>

resources/views/contact.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->

</head>
<body>

	<div class="bg-contact2" style="background-image: url('audit3.jpg');">
		<div class="container-contact2">
			<div class="wrap-contact2">
		@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
        @endif

			@if (session('status'))
				<div class="alert alert-success">
				{{ session('status') }}
				</div>
         	@endif
				<form class="contact2-form validate-form" action="{{ url('storeContact') }}" method="POST">
					<span class="contact2-form-title">
						Contact Us
					</span>

					<div class="wrap-input2 validate-input" data-validate="Name is required">
						<input class="input2" type="text" name="name">
						<span class="focus-input2" data-placeholder="NAME"></span>
					</div>

					<div class="wrap-input2 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input2" type="text" name="email">
						<span class="focus-input2" data-placeholder="EMAIL"></span>
					</div>

					<div class="wrap-input2 validate-input" data-validate = "Message is required">
						<textarea class="input2" name="message"></textarea>
						<span class="focus-input2" data-placeholder="MESSAGE"></span>
					</div>


						<input class="input2" type="hidden" name="_token" value="{{csrf_token()}}">



					<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
							<button class="contact2-form-btn">
								Send Your Message
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<footer class="container-fluid">
  <p>&copy Copyright Protected By BiGOne IT SolutionS</p>
</footer>
	</div>




<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>

</body>
</html>

resources/views/flash_message.blade.php
<style type="text/css">
  .alert{
      position: absolute;
      float: left;
      top:50px;
      width: 100%
      padding: 10px 350px;
  }
</style>
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>
	Please check the form below for errors
</div>
@endif

resources/views/headerfooter.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="shortcut icon" href="IASttl1.png"/>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="/css/amrstyle.css">
  <link rel="stylesheet" href="/css/amr.css">
  <script src="{{ asset('js/app.js') }}" defer></script>
  <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->


  <style>
    .myNav{
      color-white;
    }

    .color{
      background-color: rgb(57, 142, 192);
      border:0px;
      color-white;
    }

    .top-right1 {
               position: absolute;
               width: 100px;
               height: 30px;
               right: 70px;
               top: 8px;
           }

    .homebtn {
                position: absolute;
                width: 100px
                height: 30px;
                left: 30px;
                top: 10px;
              }     
    .btn.btn-primary{
      background-color: rgb(57, 142, 192);
      border:0px;
      color-white; 
    }         

  </style>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class navbar-left>
    <a href="{{ url('main_home') }}" class="navbar-left"><img style="max-width:100px; margin-top: -1px; max-height:50px;" src="IASicon2.png"></a>
    </div>
    <!-- <form method="get" action="/">
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <div class="homebtn">
        <button type="submit" class="color"><span class="glyphicon glyphicon-home"></span> Home</button>
        </div>
      </ul>
    </form> -->
        <ul class="nav navbar-nav navbar-right">
        <div class="top-right1">
                            <li>
                                <a class="btn btn-primary" id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                 {{ Auth::user()->fullname }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
      </div>
      </ul>
            @csrf
            <!-- <div class="top-right1"> -->
            <!-- <button type="submit" class="color"><span class="glyphicon glyphicon-log-out"></span> Logout</button> -->
            <!-- </div> -->
          </ul>

          <!-- </form> -->
        </li>
      </ul>
    </div>
  </div>
</nav>


</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/iqacnotification.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  @include('headerfooter')
  <link rel="shortcut icon" href="IASttl1.png"/>
  <title>IQAC-NOTIFICATIONS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="/css/amrstyle.css">
  <link rel="stylesheet" href="/css/amr.css">
</head>
<body>

<!-- Side Navbar -->
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IQAC HOME</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="IQAC.iqac_profile">Profile</a></li>
        <li class="active"><a href="IQAC.notification">Notifications</a></li>
        <li><a href="IQAC.view_schedule">View Schedule</a></li>
        <li><a href="IQAC.view_auditors">View Auditors</a></li>
        <li><a href="IQAC.view_report">Audit Report</a></li>
      </ul><br>
    </div>

<!-- Table Content -->
    <div class="col-sm-9">
      <h4><small>NOTIFICATIONS</small></h4>
      <hr>

    <div>
    <textarea id="notificationsubject" name="notificationsubject"  style="width:980px"></textarea>
    </div>

    </div>
  </div>


<!-- footer -->
<footer class="container-fluid">
  <p>Powered By BiGOne IT SolutionS</p>
</footer>
</div>
</body>
</html>

resources/views/main_home.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    @include('headerfooter')
    <link rel="shortcut icon" href="IASttl1.png"/>
    <title>HOME</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/css/amrstyle.css">
    <link rel="stylesheet" href="/css/amr.css">
  </head>
  <body>

    <!-- Side Navbar -->
    <div class="container-fluid">
      <div class="row content">
        <div class="col-sm-3 sidenav">
        <h4>ROLES</h4>
          <ul class="nav nav-pills nav-stacked">
          @if(Auth::user()->is_amr)
            <li ><a href="{{ url('amrhome') }}">AMR</a></li>
          @endif
          @if(Auth::user()->is_iqacco)
            <li><a href="{{ url('IQACCo.iqacco_home') }}">IQAC CO.</a></li>
          @endif
          @if(Auth::user()->is_iqac)
            <li ><a href="{{ url('IQAC.iqac_home') }}">IQAC</a></li>
          @endif
          @if(Auth::user()->is_auditee)
            <li ><a href="{{ url('AUDITEE.auditee_home') }}" @isset($menu) @if($menu == 'profile')  class="active" @endif @endisset>AUDITEE</a></li>
          @endif
          @if(Auth::user()->is_auditor)
            <li ><a href="{{ url('AUDITOR.auditor_home') }}">AUDITOR</a></li>
          @endif
          </ul><br>
        </div>
      </div>
      <main class="py-4">
          @yield('content')
      </main>
    </div>
    <footer class="container-fluid">
      <p> &copy copyright protected By BiGOne IT SolutionS</p>
    </footer>
  </body>
</html>

resources/views/test.blade.php
<!DOCTYPE html>
<html>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<body>

<div ng-app="myApp" ng-controller="myCtrl">
Name: <input ng-model="name">
</div>

<script>
var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope) {
    $scope.name = "John Doe";
});
</script>

<p>Use the ng-model directive to bind the value of the input field to a property made in the controller.</p>

</body>
</html>